name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag placeindia-commander
    - name: Stop already running image
      run: docker stop placeindia-commander-container
    - name: Delete already running image
      run: docker rm placeindia-commander-container  
    - name: Build the Docker image
      run: docker run --name placeindia-commander-container -e PASSWORD="${{secrets.npm_token}}" -p 80:3987 -d placeindia-commander:latest
